name: 6.6.89 欧加真OKI内核快速构建

env:
  TZ: Asia/Shanghai
  ANDROID_VERSION: 'android15'
  KERNEL_VERSION: '6.6'
  SUB_VERSION: '89'
  KERNEL_NAME: 'android15-8-g29d86c5fc9dd-abogki428889875-4k'
  CCACHE_KEY: ccache-ecsv2-6.6.89

on:
  workflow_dispatch:
    inputs:
      ksu_type:
        description: 'KernelSU分支(ReSukiSU/SukiSU Ultra/KernelSU Next/KSU(原版)/无内置KSU,默认ReSukiSU)'
        required: true
        type: choice
        default: 'resukisu'
        options:
          - 'resukisu'
          - 'sukisu'
          - 'ksunext'
          - 'ksu'
          - 'none'
      susfs_enable:
        description: '是否开启susfs(用于增强隐藏环境挂载功能; 可能轻微增加耗电，上游更新导致不稳定时或不需要可关闭)'
        required: true
        type: boolean
        default: 'true'
      kpm_enable:
        description: '是否开启kpm(builtin-使用(re)sukisu内置kpm, kpn-使用独立kpm实现(支持任意KSU/面具环境); 不需要可保持默认关闭)'
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'builtin'
          - 'kpn'
      lz4_enable:
        description: '是否安装 lz4 1.10.0+zstd 1.5.7 补丁'
        required: true
        type: boolean
        default: 'true'
      lz4kd_enable:
        description: '是否安装 LZ4KD 补丁(若已开启lz4+zstd补丁则可不开启)'
        required: true
        type: boolean
        default: 'false'
      bbr_enable:
        description: "是否启用bbr算法(优化上行数据,对手机日用无太大意义甚至可能负优化;false关闭,true仅加入算法,default启用算法并设为默认)"
        required: true
        type: choice
        default: 'false'
        options:
          - 'false'
          - 'true'
          - 'default'
      better_net:
        description: '是否开启网络功能拓展配置(用于为ipset及需要iptables等高级网络功能内核支持的程序提供支持)'
        required: true
        type: boolean
        default: 'false'
      adios_enable:
        description: '是否启用ADIOS IO调度器支持(提升IO读写性能)'
        required: true
        type: boolean
        default: 'true'
      rekernel_enable:
        description: '是否启用Re-Kernel支持(与Freezer/NoActive等软件配合, 提升应用冻结能力)'
        required: true
        type: boolean
        default: 'false'
      baseband_guard:
        description: '是否开启内核级基带保护(阻止一切对非用户分区的写入，有效防止格机)'
        required: true
        type: boolean
        default: 'true'
      ccache_update:
        description: '更新ccache缓存(将本次编译生成的ccache缓存覆盖至仓库缓存，在更改编译配置、源码或需要刷新缓存时开启)'
        required: true
        type: boolean
        default: 'false'
      ccache_debug:
        description: '是否上传 Ccache调试日志(用于调试, 无需要不必开启)'
        required: true
        type: boolean
        default: 'false'
      kernel_suffix:
        description: '内核后缀(留空默认,开头别加连字符,勿加空格等影响指令运行的保留字符)'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      ksuver: ${{ steps.ksu_version.outputs.ksuver }}
      ak3name: ${{ steps.create_zip.outputs.ak3name }}
    permissions:
      actions: write
      contents: read
    steps:
      - name: 安装环境依赖+初始化源码仓库及llvm-Clang18工具链
        run: |
          rm -rf kernel_workspace
          mkdir kernel_workspace
          cd kernel_workspace
          echo "当前仓库：$GITHUB_REPOSITORY"
          echo "当前分支：$GITHUB_REF_NAME"

          sudo apt-mark hold firefox &&
          sudo apt-mark hold libc-bin &&
          sudo apt purge man-db &&
          sudo rm -rf /var/lib/man-db/auto-update &&
          sudo apt update &&
          sudo apt-get install -y --no-install-recommends binutils python-is-python3 libssl-dev libelf-dev &

          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/ccache-x86-64 -O ccache &&
          sudo cp -f ./ccache /usr/bin/ccache &&
          sudo chmod +x /usr/bin/ccache &&
          rm -f ./ccache &

          echo "正在克隆源码仓库..."
          aria2c -s16 -x16 -k1M https://github.com/cctv18/android_kernel_common_oneplus_sm8750/archive/refs/heads/oneplus/sm8750_v_16.0.0_oneplus_13_6.6.89.zip -o common.zip &&
          unzip -q common.zip &&
          mv "android_kernel_common_oneplus_sm8750-oneplus-sm8750_v_16.0.0_oneplus_13_6.6.89" common &&
          rm -rf common.zip &

          echo "正在克隆llvm-clang18工具链..." &&
          mkdir -p clang18 &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang18-r510928/clang-r510928.zip -o clang.zip &&
          unzip -q clang.zip -d clang18 &&
          rm -rf clang.zip &

          echo "正在克隆构建工具..." &&
          aria2c -s16 -x16 -k1M https://github.com/cctv18/oneplus_sm8650_toolchain/releases/download/LLVM-Clang18-r510928/build-tools.zip -o build-tools.zip &&
          unzip -q build-tools.zip &&
          rm -rf build-tools.zip &

          wait
          echo "所有源码及llvm-Clang18工具链初始化完成！"
          echo "正在去除 ABI 保护 & 去除 dirty 后缀..."
          rm common/android/abi_gki_protected_exports_* || true
          for f in common/scripts/setlocalversion; do
            sed -i 's/ -dirty//g' "$f"
            sed -i '$i res=$(echo "$res" | sed '\''s/-dirty//g'\'')' "$f"
          done

      - name: 配置ccache目录
        run: |
          echo "CCACHE_DIR=$HOME/.ccache_${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}" >> $GITHUB_ENV
          echo "CCACHE_MAXSIZE=3G" >> $GITHUB_ENV
          echo "当前磁盘空间："
          df -h
          echo "当前构建内核版本：${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}"

      - name: 载入当前版本内核的 ccache缓存
        uses: actions/cache@v5
        id: ccache-restore
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CCACHE_KEY }}-${{ runner.os }}-${{ github.ref_name }}
          restore-keys: |
            ${{ env.CCACHE_KEY }}-${{ runner.os }}-
            ${{ env.CCACHE_KEY }}-

      - name: 拉取公共预置 ccache 缓存
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "检查本地缓存状态..."
          if [ -d "${{ env.CCACHE_DIR }}" ] && [ "$(ls -A ${{ env.CCACHE_DIR }} 2>/dev/null)" ]; then
            echo "检测到本地已成功载入 ccache 缓存，跳过公共 ccache 拉取！"
            exit 0
          fi
          echo "未命中缓存，尝试拉取最新公共 ccache ..."
          mkdir -p ${{ env.CCACHE_DIR }}
          FILE_NAME="ccache-${{ env.KERNEL_VERSION }}.${{ env.SUB_VERSION }}.tar.zst"
          if gh release download -p "$FILE_NAME" -R cctv18/public_ccache; then
            echo "成功下载 $FILE_NAME，正在解压..."
            tar -I zstd -xf "$FILE_NAME" -C ${{ env.CCACHE_DIR }}
            echo "公共 ccache 恢复完成！"
          else
            echo "公共 ccache 中未找到对应的 ccache 文件，将进行全量全新编译..."
          fi

      - name: 清除旧 ccache 缓存
        if: inputs.ccache_update
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "正在清除仓库中的旧 ccache 缓存..."
          if gh cache delete ${{ env.CCACHE_KEY }}-${{ runner.os }}-${{ github.ref_name }} -R ${{ github.repository }}; then
            echo "成功删除旧的 ccache 缓存！"
          else
            echo "旧缓存不存在或已被清理！"
          fi

      - name: 初始化并配置ccache
        run: |
          export CCACHE_COMPILERCHECK="none"
          export CCACHE_BASEDIR="${{ github.workspace }}"
          export CCACHE_NOHASHDIR="true"
          export CCACHE_NOHARDLINK="true"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="${{ env.CCACHE_MAXSIZE }}"
          mkdir -p "$CCACHE_DIR"
          ccache -M "$CCACHE_MAXSIZE"
          ccache -o compression=true
          ccache -s

      - name: 添加KernelSU
        id: ksu_version
        run: |
          cd kernel_workspace
          if [[ ${{ github.event.inputs.ksu_type }} == "sukisu" ]]; then
            curl -LSs "https://raw.githubusercontent.com/ShirkNeko/SukiSU-Ultra/refs/heads/main/kernel/setup.sh" | bash -s builtin
            cd ./KernelSU
            GIT_COMMIT_HASH=$(git rev-parse --short=8 HEAD)
            KSU_API_VERSION=$(curl -s "https://raw.githubusercontent.com/SukiSU-Ultra/SukiSU-Ultra/builtin/kernel/Makefile" | grep -m1 "KSU_VERSION_API :=" | awk -F'= ' '{print $2}' | tr -d '[:space:]')
            [ -z "$KSU_API_VERSION" ] && KSU_API_VERSION="3.1.7"
            echo "KSU_API_VERSION=$KSU_API_VERSION" >> $GITHUB_ENV
            VERSION_DEFINITIONS=$'define get_ksu_version_full\nv\\$1-'"$GIT_COMMIT_HASH"$'@cctv18\nendef\n\nKSU_VERSION_API := '"$KSU_API_VERSION"$'\nKSU_VERSION_FULL := v'"$KSU_API_VERSION"$'-'"$GIT_COMMIT_HASH"$'@cctv18'
            sed -i '/define get_ksu_version_full/,/endef/d' kernel/Makefile
            sed -i '/KSU_VERSION_API :=/d' kernel/Makefile
            sed -i '/KSU_VERSION_FULL :=/d' kernel/Makefile
            awk -v def="$VERSION_DEFINITIONS" '/REPO_OWNER :=/ {print; print def; inserted=1; next} 1 END {if (!inserted) print def}' kernel/Makefile > kernel/Makefile.tmp && mv kernel/Makefile.tmp kernel/Makefile
            KSU_VERSION=$(expr $(git rev-list --count main) + 37185 2>/dev/null || echo 114514)
            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.ksu_type }} == "resukisu" ]]; then
            curl -LSs "https://raw.githubusercontent.com/ReSukiSU/ReSukiSU/refs/heads/main/kernel/setup.sh" | bash -s main
            echo 'CONFIG_KSU_FULL_NAME_FORMAT="%TAG_NAME%-%COMMIT_SHA%@cctv18"' >> ./common/arch/arm64/configs/gki_defconfig
            cd ./KernelSU
            KSU_VERSION=$(expr $(git rev-list --count main) + 30700 2>/dev/null || echo 114514)
            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksunext" ]]; then
            curl -LSs "https://raw.githubusercontent.com/pershoot/KernelSU-Next/refs/heads/dev-susfs/kernel/setup.sh" | bash -s dev-susfs
            cd KernelSU-Next
            rm -rf .git
            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/pershoot/KernelSU-Next/commits?sha=dev&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
            sed -i "s/KSU_VERSION_FALLBACK := 1/KSU_VERSION_FALLBACK := $KSU_VERSION/g" kernel/Kbuild
            KSU_GIT_TAG=$(curl -sL "https://api.github.com/repos/KernelSU-Next/KernelSU-Next/tags" | grep -o '"name": *"[^"]*"' | head -n 1 | sed 's/"name": "//;s/"//')
            sed -i "s/KSU_VERSION_TAG_FALLBACK := v0.0.1/KSU_VERSION_TAG_FALLBACK := $KSU_GIT_TAG/g" kernel/Kbuild
            cd ../common/drivers/kernelsu
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/apk_sign.patch
            patch -p2 -N -F 3 < apk_sign.patch || true
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksu" ]]; then
            curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/refs/heads/main/kernel/setup.sh" | bash -s main
            cd ./KernelSU
            KSU_VERSION=$(expr $(curl -sI "https://api.github.com/repos/tiann/KernelSU/commits?sha=main&per_page=1" | grep -i "link:" | sed -n 's/.*page=\([0-9]*\)>; rel="last".*/\1/p') "+" 30000)
            echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
            echo "ksuver=$KSU_VERSION" >> $GITHUB_OUTPUT
            sed -i "s/DKSU_VERSION=16/DKSU_VERSION=${KSU_VERSION}/" kernel/Kbuild
          fi

      - name: 应用 KernelSU & SUSFS 补丁
        if: inputs.susfs_enable
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd kernel_workspace
          # 修复认证问题
          git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"
          
          if [[ ${{ github.event.inputs.ksu_type }} != "none" ]]; then
            echo "正在从 GitLab 获取 susfs v1.5.12 补丁..."
            # 修复补丁源地址
            git clone --depth=1 --branch v1.5.12 https://gitlab.com/simonpunk/susfs4ksu.git susfs4ksu
            git clone --depth=1 https://github.com/cctv18/susfs4oki.git susfs4oki -b oki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}
            wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/69_hide_stuff.patch -O ./common/69_hide_stuff.patch
            cp ./susfs4ksu/kernel_patches/50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch ./common/
            cp ./susfs4oki/kernel_patches/fs/* ./common/fs/
            cp ./susfs4oki/kernel_patches/include/linux/* ./common/include/linux/
            cd ./common
            patch -p1 < 50_add_susfs_in_gki-${{ env.ANDROID_VERSION }}-${{ env.KERNEL_VERSION }}.patch || true
            patch -p1 -N -F 3 < 69_hide_stuff.patch || true
            cd ..
          fi

          if [[ ${{ github.event.inputs.ksu_type }} == "resukisu" || ${{ github.event.inputs.ksu_type }} == "sukisu" ]]; then
            cp ./susfs4ksu/kernel_patches/SukiSU/10_enable_susfs_for_sukisu.patch ./KernelSU/
            cd ./KernelSU && patch -p1 < 10_enable_susfs_for_sukisu.patch || true
            cd ..
          elif [[ ${{ github.event.inputs.ksu_type }} == "ksu" ]]; then
            cp ./susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./KernelSU/
            cd ./KernelSU && patch -p1 < 10_enable_susfs_for_ksu.patch || true
            cd ..
          fi

      - name: 应用lz4 1.10.0 & zstd 1.5.7补丁
        if: inputs.lz4_enable
        run: |
          cd kernel_workspace
          git clone --depth=1 https://github.com/$GITHUB_REPOSITORY.git -b $GITHUB_REF_NAME $GITHUB_ACTOR
          cp ./$GITHUB_ACTOR/zram_patch/001-lz4.patch ./common/
          cp ./$GITHUB_ACTOR/zram_patch/lz4armv8.S ./common/lib
          cp ./$GITHUB_ACTOR/zram_patch/002-zstd.patch ./common/
          cd ./common
          git apply -p1 < 001-lz4.patch || true
          patch -p1 < 002-zstd.patch || true

      - name: 应用 lz4kd 补丁
        if: inputs.lz4kd_enable
        run: |
          cd kernel_workspace
          if [ ! -d "SukiSU_patch" ]; then git clone --depth=1 https://github.com/ShirkNeko/SukiSU_patch.git; fi
          cd common
          cp -r ../SukiSU_patch/other/zram/lz4k/include/linux/* ./include/linux/
          cp -r ../SukiSU_patch/other/zram/lz4k/lib/* ./lib
          cp -r ../SukiSU_patch/other/zram/lz4k/crypto/* ./crypto
          cp ../SukiSU_patch/other/zram/zram_patch/${{ env.KERNEL_VERSION }}/lz4kd.patch ./
          patch -p1 -F 3 < lz4kd.patch || true

      - name: 添加SUSFS 配置项
        if: inputs.susfs_enable
        run: |
          cd kernel_workspace
          {
            echo "CONFIG_KSU_SUSFS=y"
            echo "CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_SUS_PATH=y"
            echo "CONFIG_KSU_SUSFS_SUS_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_SUS_KSTAT=y"
            echo "CONFIG_KSU_SUSFS_TRY_UMOUNT=y"
            echo "CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y"
            echo "CONFIG_KSU_SUSFS_SPOOF_UNAME=y"
            echo "CONFIG_KSU_SUSFS_ENABLE_LOG=y"
            echo "CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y"
            echo "CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y"
            echo "CONFIG_KSU_SUSFS_OPEN_REDIRECT=y"
            echo "CONFIG_KSU_SUSFS_SUS_MAP=y"
          } >> ./common/arch/arm64/configs/gki_defconfig

      - name: 添加 KSU & 其他配置项
        run: |
          cd kernel_workspace
          echo "CONFIG_KSU=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [[ ${{ github.event.inputs.kpm_enable }} == 'builtin' && ( "${{ github.event.inputs.ksu_type }}" == "sukisu" || "${{ github.event.inputs.ksu_type }}" == "resukisu" ) ]]; then
            echo "CONFIG_KPM=y" >> ./common/arch/arm64/configs/gki_defconfig
          fi
          [[ "${{ github.event.inputs.susfs_enable }}" == "false" ]] && echo "CONFIG_KSU_SUSFS=n" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_XATTR=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_TMPFS_POSIX_ACL=y" >> ./common/arch/arm64/configs/gki_defconfig
          if [[ "${{ github.event.inputs.lz4kd_enable }}" == "true" ]]; then
            {
              echo "CONFIG_ZSMALLOC=y"
              echo "CONFIG_CRYPTO_LZ4HC=y"
              echo "CONFIG_CRYPTO_LZ4K=y"
              echo "CONFIG_CRYPTO_LZ4KD=y"
              echo "CONFIG_CRYPTO_842=y"
            } >> ./common/arch/arm64/configs/gki_defconfig
          fi
          echo "CONFIG_CC_OPTIMIZE_FOR_PERFORMANCE=y" >> ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/check_defconfig//' ./common/build.config.gki
          echo "CONFIG_HEADERS_INSTALL=n" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 启用网络功能增强优化配置
        if: inputs.better_net
        run: |
          cd kernel_workspace
          {
            echo "CONFIG_BPF_STREAM_PARSER=y"
            echo "CONFIG_NETFILTER_XT_MATCH_ADDRTYPE=y"
            echo "CONFIG_NETFILTER_XT_SET=y"
            echo "CONFIG_IP_SET=y"
            echo "CONFIG_IP_SET_MAX=65534"
            echo "CONFIG_IP_SET_BITMAP_IP=y"
            echo "CONFIG_IP_SET_BITMAP_IPMAC=y"
            echo "CONFIG_IP_SET_BITMAP_PORT=y"
            echo "CONFIG_IP_SET_HASH_IP=y"
            echo "CONFIG_IP_SET_HASH_IPMARK=y"
            echo "CONFIG_IP_SET_HASH_IPPORT=y"
            echo "CONFIG_IP_SET_HASH_IPPORTIP=y"
            echo "CONFIG_IP_SET_HASH_IPPORTNET=y"
            echo "CONFIG_IP_SET_HASH_IPMAC=y"
            echo "CONFIG_IP_SET_HASH_MAC=y"
            echo "CONFIG_IP_SET_HASH_NETPORTNET=y"
            echo "CONFIG_IP_SET_HASH_NET=y"
            echo "CONFIG_IP_SET_HASH_NETNET=y"
            echo "CONFIG_IP_SET_HASH_NETPORT=y"
            echo "CONFIG_IP_SET_HASH_NETIFACE=y"
            echo "CONFIG_IP_SET_LIST_SET=y"
            echo "CONFIG_IP6_NF_NAT=y"
            echo "CONFIG_IP6_NF_TARGET_MASQUERADE=y"
          } >> ./common/arch/arm64/configs/gki_defconfig
          cd common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/other_patch/config.patch
          patch -p1 -F 3 < config.patch || true

      - name: 添加 BBR 等一系列拥塞控制算法
        run: |
          if [[ "${{ github.event.inputs.bbr_enable }}" != "false" ]]; then
            cd kernel_workspace
            {
              echo "CONFIG_TCP_CONG_ADVANCED=y"
              echo "CONFIG_TCP_CONG_BBR=y"
              echo "CONFIG_TCP_CONG_CUBIC=y"
              echo "CONFIG_TCP_CONG_VEGAS=y"
              echo "CONFIG_TCP_CONG_NV=y"
              echo "CONFIG_TCP_CONG_WESTWOOD=y"
              echo "CONFIG_TCP_CONG_HTCP=y"
              echo "CONFIG_TCP_CONG_BRUTAL=y"
            } >> ./common/arch/arm64/configs/gki_defconfig
            if [[ "${{ github.event.inputs.bbr_enable }}" == "default" ]]; then
              echo "CONFIG_DEFAULT_TCP_CONG=bbr" >> ./common/arch/arm64/configs/gki_defconfig
            else
              echo "CONFIG_DEFAULT_TCP_CONG=cubic" >> ./common/arch/arm64/configs/gki_defconfig
            fi
          fi

      - name: 启用ADIOS IO调度器
        if: inputs.adios_enable
        run: |
          cd kernel_workspace
          echo "CONFIG_MQ_IOSCHED_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig
          echo "CONFIG_MQ_IOSCHED_DEFAULT_ADIOS=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 启用Re-Kernel支持
        if: inputs.rekernel_enable
        run: |
          cd kernel_workspace
          echo "CONFIG_REKERNEL=y" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 启用内核级基带保护
        if: inputs.baseband_guard
        run: |
          cd kernel_workspace
          echo "CONFIG_BBG=y" >> ./common/arch/arm64/configs/gki_defconfig
          cd ./common
          curl -sSL https://github.com/cctv18/Baseband-guard/raw/master/setup.sh | bash
          sed -i '/^config LSM$/,/^help$/{ /^[[:space:]]*default/ { /baseband_guard/! s/selinux/selinux,baseband_guard/ } }' security/Kconfig

      - name: 添加制作名称
        run: |
          cd kernel_workspace
          if [[ -n "${{ github.event.inputs.kernel_suffix }}" ]]; then
            SUFFIX="${{ github.event.inputs.kernel_suffix }}"
          else
            SUFFIX="${{ env.KERNEL_NAME }}"
          fi
          for f in ./common/scripts/setlocalversion; do
            sed -i "\$s|echo \"\\\$res\"|echo \"-$SUFFIX\"|" "$f"
          done
          sudo sed -i "s/-4k/-$SUFFIX/g" ./common/arch/arm64/configs/gki_defconfig
          sed -i 's/${scm_version}//' ./common/scripts/setlocalversion
          echo "CONFIG_LOCALVERSION_AUTO=n" >> ./common/arch/arm64/configs/gki_defconfig

      - name: 构建内核
        run: |
          WORKDIR="$(pwd)"
          export PATH="/usr/lib/ccache:$WORKDIR/kernel_workspace/clang18/bin:$WORKDIR/kernel_workspace/build-tools/bin:$PATH"
          export CCACHE_DIR="${{ env.CCACHE_DIR }}"
          export CCACHE_MAXSIZE="3G"
          cd kernel_workspace/common
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/libfakestat.so
          wget https://github.com/$GITHUB_REPOSITORY/raw/refs/heads/$GITHUB_REF_NAME/lib/libfaketimeMT.so
          chmod 777 ./*.so
          export FAKESTAT="2025-05-25 12:00:00"
          export FAKETIME="@2025-05-25 13:00:00"
          SO_DIR=$(pwd)
          export PRELOAD_LIBS="$SO_DIR/libfakestat.so $SO_DIR/libfaketimeMT.so"

          echo -e '#!/bin/bash\nexport LD_PRELOAD="'$PRELOAD_LIBS'"\nexport FAKESTAT="'$FAKESTAT'"\nexport FAKETIME="'$FAKETIME'"\nccache clang "$@"' > cc-wrapper
          echo -e '#!/bin/bash\nexport LD_PRELOAD="'$PRELOAD_LIBS'"\nexport FAKESTAT="'$FAKESTAT'"\nexport FAKETIME="'$FAKETIME'"\nld.lld "$@"' > ld-wrapper
          chmod +x cc-wrapper ld-wrapper

          sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="ccache clang" LD="ld.lld" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error gki_defconfig
          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC="$(pwd)/cc-wrapper" LD="$(pwd)/ld-wrapper" HOSTLD=ld.lld O=out KCFLAGS+=-O2 KCFLAGS+=-Wno-error Image

      - name: 保存新的 ccache 缓存
        if: inputs.ccache_update || steps.ccache-restore.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: ${{ env.CCACHE_DIR }}
          key: ${{ env.CCACHE_KEY }}-${{ runner.os }}-${{ github.ref_name }}

      - name: 应用KPM并修补内核
        run: |
          cd kernel_workspace/common/out/arch/arm64/boot
          if [[ ${{ github.event.inputs.kpm_enable }} == 'builtin' ]]; then
            curl -LO https://github.com/SukiSU-Ultra/SukiSU_KernelPatch_patch/releases/latest/download/patch_linux
            chmod +x patch_linux && ./patch_linux && mv oImage Image
          elif [[ ${{ github.event.inputs.kpm_enable }} == 'kpn' ]]; then
            wget https://github.com/KernelSU-Next/KPatch-Next/releases/latest/download/kptools-linux
            wget https://github.com/KernelSU-Next/KPatch-Next/releases/latest/download/kpimg-linux
            chmod +x ./kptools-linux && ./kptools-linux -p -i ./Image -k ./kpimg-linux -o ./oImage && mv oImage Image
          fi

      - name: 克隆 AnyKernel3 并打包
        id: create_zip
        run: |
          cd kernel_workspace
          git clone https://github.com/cctv18/AnyKernel3 --depth=1 && rm -rf ./AnyKernel3/.git
          cd AnyKernel3
          cp ../common/out/arch/arm64/boot/Image ./Image
          [[ ! -f ./Image ]] && exit 1
          KSU_MAP=("sukisu:SukiSU" "resukisu:ReSukiSU" "ksunext:KSUNext" "ksu:KSU")
          KSU_TYPENAME="none"
          for pair in "${KSU_MAP[@]}"; do [[ "${pair%%:*}" == "${{ github.event.inputs.ksu_type }}" ]] && KSU_TYPENAME="${pair#*:}"; done
          [[ "${{ github.event.inputs.lz4kd_enable }}" == "true" ]] && wget https://raw.githubusercontent.com/$GITHUB_REPOSITORY/refs/heads/$GITHUB_REF_NAME/zram.zip
          [[ ${{ github.event.inputs.kpm_enable }} == 'kpn' ]] && wget https://github.com/cctv18/KPatch-Next/releases/latest/download/kpn.zip
          AK3_NAME="AnyKernel3_${KSU_TYPENAME}_${{ env.KSUVER }}_${{ env.KERNEL_VERSION }}_${{ github.event.inputs.kernel_suffix || env.KERNEL_NAME }}.zip"
          zip -r ../$AK3_NAME ./*
          echo "ak3name=$AK3_NAME" >> $GITHUB_OUTPUT

      - name: 上传 ZIP 工件
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/kernel_workspace/AnyKernel*.zip
          archive: false

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: 下载 ZIP 工件
        uses: actions/download-artifact@v8
        with:
          path: ./release_zips
      - name: 发布 Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG="OPPO-OPlus-Realme-build-$(date +'%y%m%d%H%M%S')"
          gh release create "$TAG" release_zips/**/*.zip --title "SM8750 内核更新" --notes "基于一加13源码构建"
